name: Windows
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/core/.local-chromium
          key: >
            ${{ runner.os }}/node-14/
            ${{ hashFiles('.github/.cache-key') }}/
            ${{ hashFiles('**/yarn.lock') }}
          restore-keys: >
            ${{ runner.os }}/node-14/
            ${{ hashFiles('.github/.cache-key') }}/
      - run: yarn
      - run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: packages/*/dist

  test:
    name: Test ${{ matrix.package }}
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        package:
          - '@tipalti/percy-env'
          - '@tipalti/percy-client'
          - '@tipalti/percy-dom'
          - '@tipalti/percy-logger'
          - '@tipalti/percy-config'
          - '@tipalti/percy-core'
          - '@tipalti/percy-cli'
          - '@tipalti/percy-cli-command'
          - '@tipalti/percy-cli-exec'
          - '@tipalti/percy-cli-snapshot'
          - '@tipalti/percy-cli-upload'
          - '@tipalti/percy-cli-build'
          - '@tipalti/percy-cli-config'
          - '@tipalti/percy-sdk-utils'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/core/.local-chromium
          key: >
            ${{ runner.os }}/node-14/
            ${{ hashFiles('.github/.cache-key') }}/
            ${{ hashFiles('**/yarn.lock') }}
          restore-keys: >
            ${{ runner.os }}/node-14/
            ${{ hashFiles('.github/.cache-key') }}/
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: packages
      - run: yarn
      - name: Run tests
        run: yarn workspace ${{ matrix.package }} test --colors
